spring:
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300 # 配置IP及端口号
#节点的地址 注意api模式下端口号是9300，千万不要写成9200
      cluster-name: elasticsearch
#      cluster-name: elasticsearch622 # 配置集群名，默认为elasticsearch，如果手动更改过，这里一定要指定
#是否开启本地存储
      repositories:
        enabled: true


